import Head from "next/head";
import React from "react";
import { Sidebar } from "@/components/sidebar";
import { Feed } from "@/components/feed";
import FilterDrawer from "@/components/filter-drawer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Localist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <main className="p-4 sm:ml-64">
        <FilterDrawer />
        <Feed />
      </main>
    </>
  );
}
